name: Community Submission
title: Community
description: Fill the information to allow BeloBTC team handle your community creation issue
body:
- type: input
  id: communityName
  attributes:
    label: Community
    description: "Name of community to appear on BTCMAP"
    placeholder: "12334
  validations:
    required: true
- type: dropdown
  id: areaType
  attributes:
    label: Area type
    options:
      - Community
  validations:
    required: true
- type: input
  id: issueId
  attributes:
    label: Issue Id
    description: "Gitea BTCMAP issue id"
    placeholder: "12334"
- type: input
  id: OSMId
  attributes:
    label: OSM Id
    description: "Open Street map identifier"
    placeholder: "12334"
  validations:
    required: true


